### ISSUE TITLE
Update to Babel

### ISSUE THREAD

**Issue by jamiebuilds** [reggi/react-component-webpack-example#1]
6to5 has been [renamed to Babel](http://babeljs.io/blog/2015/02/15/not-born-to-die/) and has had many releases since then.

**Comment by jamiebuilds** [comment]
ping, just trying to close out old issues.

**Comment by reggi** [comment]
Hey @thejameskyle, What's up? You just want me to update 6to5 to Babel?

**Comment by jamiebuilds** [comment]
Yeah, I was just going through and making sure that people weren't left behind when the name changed.
